version: "3.9"

services:
  #MongoDB services
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    volumes:
      - mongo_db:/data/db

  #Node/Express API service
  api:
    build: .
    ports:
      - 3002:3001
    environment:
      MONGODB_URI: "mongodb://mongo_db:27017"
      PORT: 3001
      ETHGASSTATION_URI: "https://ethgasstation.info/api/ethgasAPI.json?api-key="
      ETHGASSTATION_API_KEY: #API-KEY-HERE
    depends_on:
      - mongo_db

volumes:
  mongo_db: {}
